# Generated by Django 5.2.13 on 2026-05-01 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoastPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('outfit', 'Roast My Outfit'), ('face', 'Roast My Face'), ('setup', 'Roast My Setup'), ('resume', 'Roast My Resume'), ('dating_profile', 'Roast My Dating Profile'), ('portfolio', 'Roast My Portfolio'), ('room', 'Roast My Room'), ('bio', 'Roast My Bio')], max_length=32)),
                ('roast_style', models.CharField(choices=[('friendly', 'Friendly Roast'), ('brutal', 'Brutal Roast'), ('gen_z', 'Gen Z Mode'), ('corporate', 'Corporate Reviewer'), ('anime_villain', 'Anime Villain'), ('therapist', 'Therapist But Honest'), ('british', 'British Insult Mode')], default='friendly', max_length=32)),
                ('media', models.ImageField(blank=True, null=True, upload_to='roasts/%Y/%m/')),
                ('media_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('text_content', models.TextField(blank=True)),
                ('ai_roast', models.TextField(blank=True)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('aura', models.CharField(blank=True, max_length=120)),
                ('vibe_tags', models.JSONField(blank=True, default=list)),
                ('improvement_tips', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('followers', 'Followers')], default='public', max_length=16)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('moderation_status', models.JSONField(blank=True, default=dict)),
                ('reaction_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('bookmark_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('heat_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roast_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment'), ('hate', 'Hate or slurs'), ('sexual', 'Sexual content'), ('violence', 'Violence'), ('spam', 'Spam'), ('other', 'Other')], max_length=24)),
                ('details', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('roast_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='roasts.roastpost')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_type', models.CharField(choices=[('fire', 'Fire'), ('laugh', 'Laugh'), ('wow', 'Wow'), ('sparkles', 'Sparkles'), ('helpful', 'Helpful')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roast_reactions', to=settings.AUTH_USER_MODEL)),
                ('roast_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='roasts.roastpost')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=600)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roast_comments', to=settings.AUTH_USER_MODEL)),
                ('roast_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='roasts.roastpost')),
            ],
            options={
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('roast_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='roasts.roastpost')),
            ],
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(-1, 'Downvote'), (1, 'Upvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='roasts.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'comment'), name='unique_comment_vote')],
            },
        ),
        migrations.AddIndex(
            model_name='roastpost',
            index=models.Index(fields=['status', 'visibility', '-created_at'], name='roasts_roas_status_dc44eb_idx'),
        ),
        migrations.AddIndex(
            model_name='roastpost',
            index=models.Index(fields=['category', 'status', '-created_at'], name='roasts_roas_categor_831009_idx'),
        ),
        migrations.AddIndex(
            model_name='roastpost',
            index=models.Index(fields=['-heat_score', '-created_at'], name='roasts_roas_heat_sc_a8a0b7_idx'),
        ),
        migrations.AddIndex(
            model_name='roastpost',
            index=models.Index(fields=['user', '-created_at'], name='roasts_roas_user_id_74c46c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_resolved', '-created_at'], name='roasts_repo_is_reso_2d95b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=('user', 'roast_post', 'emoji_type'), name='unique_post_reaction'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['roast_post', '-created_at'], name='roasts_comm_roast_p_e72362_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='roasts_comm_user_id_73b5fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(fields=('user', 'roast_post'), name='unique_bookmark'),
        ),
    ]
